channels:
- conda-forge
dependencies:
- aimsgb =0.1.1
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.7.0
- matplotlib-base =3.6.0
- mendeleev =0.10.0
- numpy =1.23.3
- pandas =1.5.0
- phonopy =2.15.1
- pint =0.19.2
- pyiron_base =0.5.24
- pymatgen =2022.9.21
- pyscal =2.10.15
- scipy =1.9.1
- seekpath =2.0.1
- scikit-learn =1.1.2
- spglib =2.0.1
- ipywidgets < 8
- mp-api =0.27.5
