channels:
  - conda-forge
dependencies:
  - aimsgb =0.1.0
  - ase =3.21.1
  - coveralls
  - coverage
  - codacy-coverage
  - defusedxml =0.7.1
  - future =0.18.2
  - h5py =3.1.0
  - matplotlib-base =3.3.4
  - mendeleev =0.7.0
  - numpy =1.20.1
  - pandas =1.2.3
  - phonopy =2.9.3
  - pyiron_base =0.2.7
  - pymatgen =2022.0.5
  - pyscal =2.10.12
  - pytables =3.6.1
  - scipy =1.6.1
  - seekpath =2.0.1
  - six =1.15.0
  - scikit-learn =0.24.1
  - spglib =1.16.1
