channels:
  - conda-forge
dependencies:
  - ase >=3.21.0
  - coveralls
  - coverage
  - codacy-coverage
  - defusedxml >=0.6.0
  - future >=0.18.2
  - h5py >=3.1.0
  - matplotlib-base >=3.3.3
  - mendeleev >=0.6.1
  - molmod >=1.4.8
  - numpy >=1.20.0
  - pandas >=1.2.0
  - phonopy >=2.8.1
  - pymatgen >=2020.12.31
  - pyiron_base >=0.1.44
  - pyscal >=2.10.7
  - pytables >=3.6.1
  - quickff >=2.2.4
  - scipy >=1.6.0
  - seekpath >=1.9.5
  - six >=1.15.0
  - scikit-learn >=0.24.0
  - spglib >=1.16.0
  - tamkin >=1.2.6
  - yaff >=1.4.2
