channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- aimsgb =1.1.0
- ase =3.23.0
- atomistics =0.1.32
- defusedxml =0.7.1
- h5py =3.12.1
- matplotlib-base =3.9.2
- mendeleev =0.19.0
- mp-api =0.42.2
- numpy =1.26.4
- pandas =2.2.3
- phonopy =2.30.1
- pint =0.24.4
- pyiron_base =0.10.8
- pyiron_snippets =0.1.4
- pylammpsmpi =0.2.26
- pyscal3 =3.2.7
- scikit-learn =1.5.2
- scipy =1.14.1
- seekpath =2.1.0
- spglib =2.5.0
- structuretoolkit =0.0.28
- pyxtal =0.6.2
- jupyter-book =1.0.0
