channels:
- conda-forge
dependencies:
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.8.0
- matplotlib-base =3.7.1
- mendeleev =0.13.1
- mp-api =0.33.3
- numpy =1.24.3
- pandas =2.0.2
- phonopy =2.19.1
- pint =0.22
- pyiron_base =0.5.42
- pymatgen =2023.5.31
- pyscal =2.10.18
- scikit-learn =1.2.2
- scipy =1.10.1
- seekpath =2.1.0
- spglib =2.0.2
- structuretoolkit =0.0.3
