channels:
- conda-forge
dependencies:
- aimsgb =0.1.0
- ase =3.22.0
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- future =0.18.2
- h5py =3.5.0
- matplotlib-base =3.5.0
- mendeleev =0.9.0
- numpy =1.21.4
- pandas =1.3.4
- phonopy =2.12.0
- pyiron_base =0.4.2
- pymatgen =2022.0.16
- pyscal =2.10.12
- pytables =3.6.1
- scipy =1.7.2
- seekpath =2.0.1
- scikit-learn =1.0.1
- spglib =1.16.2
