channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- aimsgb =1.1.0
- ase =3.23.0
- atomistics =0.1.31
- defusedxml =0.7.1
- h5py =3.11.0
- matplotlib-base =3.9.2
- mendeleev =0.17.0
- mp-api =0.42.1
- numpy =1.26.4
- pandas =2.2.2
- phonopy =2.26.6
- pint =0.24.3
- pyiron_base =0.9.12
- pyiron_snippets =0.1.4
- pylammpsmpi =0.2.23
- pyscal3 =3.2.7
- scikit-learn =1.5.1
- scipy =1.14.0
- seekpath =2.1.0
- spglib =2.5.0
- structuretoolkit =0.0.27
- pyxtal =0.6.2
- jupyter-book =1.0.0
