channels:
  - conda-forge
dependencies:
  - aimsgb =0.1.0
  - ase =3.21.1
  - coveralls
  - coverage
  - codacy-coverage
  - defusedxml =0.6.0
  - future =0.18.2
  - h5py =3.2.0
  - matplotlib-base =3.3.4
  - mendeleev =0.6.1
  - molmod =1.4.8
  - numpy =1.20.1
  - pandas =1.2.3
  - phonopy =2.8.1
  - pyiron_base =0.2.2
  - pymatgen =2021.2.16
  - pyscal =2.10.7
  - pytables =3.6.1
  - quickff =2.2.4
  - scipy =1.6.0
  - seekpath =2.0.1
  - six =1.15.0
  - scikit-learn =0.24.1
  - spglib =1.16.1
  - tamkin =1.2.6
  - yaff =1.4.2
