channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.22.1
- atomistics =0.1.24
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.10.0
- matplotlib-base =3.8.3
- mendeleev =0.15.0
- mp-api =0.41.2
- numpy =1.26.4
- pandas =2.2.1
- phonopy =2.22.0
- pint =0.23
- pyiron_base =0.8.0
- pylammpsmpi =0.2.15
- pyscal =2.10.18
- scikit-learn =1.4.1.post1
- scipy =1.12.0
- seekpath =2.1.0
- spglib =2.3.1
- structuretoolkit =0.0.21
- pyxtal =0.6.2
