channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.0.5
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.9.0
- matplotlib-base =3.8.0
- mendeleev =0.14.0
- mp-api =0.36.1
- numpy =1.24.3
- pandas =2.1.1
- phonopy =2.20.0
- pint =0.22
- pyiron_base =0.6.6
- pyscal =2.10.18
- scikit-learn =1.3.1
- scipy =1.11.3
- seekpath =2.1.0
- spglib =2.1.0
- structuretoolkit =0.0.11
