channels:
- conda-forge
dependencies:
- aimsgb =0.1.1
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.7.0
- matplotlib-base =3.6.1
- mendeleev =0.11.0
- numpy =1.23.4
- pandas =1.5.0
- phonopy =2.15.1
- pint =0.19.2
- pyiron_base =0.5.26
- pymatgen =2022.9.21
- pyscal =2.10.18
- scipy =1.9.2
- seekpath =2.0.1
- scikit-learn =1.1.2
- spglib =2.0.1
- mp-api =0.29.1
