# This workflow is used to check backwards compatibility

name: Backwards

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Merge environments
      run: |
        cp .ci_support/environment.yml environment.yml
        tail --lines=+4 .ci_support/environment-notebooks.yml >> environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        ./.ci_support/test_backwards.sh
