# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Notebooks for Integration Tests

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'integration' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        channel-priority: strict
        environment-file: .ci_support/environment.yml
        auto-activate-base: false
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
        conda env update --name test --file .ci_support/environment-notebooks.yml
    - name: Tests
      shell: bash -l {0}
      run: ./.ci_support/build_integration_notebooks.sh
