# This workflow is used to test, if the code is compatible with jupyter notebooks providing usage examples

name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge environment
        run: |
          cp .ci_support/environment.yml environment.yml
          tail --lines=+4 .ci_support/environment-notebooks.yml >> environment.yml
          echo "channels:\n  - conda-forge\npkgs_dirs:\n  - /home/runner/conda_pkgs_dir" > .condarc
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.12'
          miniforge-version: latest
          condarc-file: .condarc
          activate-environment: my-env
          environment-file: environment.yml
      - name: Test
        shell: bash -l {0}
        run: |
          pip install versioneer[toml]==0.29
          pip install . --no-deps --no-build-isolation
          ./.ci_support/build_notebooks.sh
