name: Unittest Lower Bound

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge or load cache
      uses: pyiron/actions/cached-miniforge@v3.2.1
      with:
        python-version: '3.9'
        miniforge-variant: Mambaforge
        miniforge-channels: conda-forge
        miniforge-channel-priority: strict
        env-path: 'cached-miniforge/my-env'
        env-files: .ci_support/environment-old.yml
        miniforge-use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        python .ci_support/pyironconfig.py
        pip install versioneer[toml]==0.29
        pip install . --no-deps --no-build-isolation
        python -m unittest discover tests
